// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/learning.proto

package learning

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddMaterialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "TEXT" or "LINK"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMaterialRequest) Reset() {
	*x = AddMaterialRequest{}
	mi := &file_proto_learning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMaterialRequest) ProtoMessage() {}

func (x *AddMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_learning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMaterialRequest.ProtoReflect.Descriptor instead.
func (*AddMaterialRequest) Descriptor() ([]byte, []int) {
	return file_proto_learning_proto_rawDescGZIP(), []int{0}
}

func (x *AddMaterialRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddMaterialRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AddMaterialResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MaterialId        string                 `protobuf:"bytes,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	FlashcardsCreated int32                  `protobuf:"varint,2,opt,name=flashcards_created,json=flashcardsCreated,proto3" json:"flashcards_created,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddMaterialResponse) Reset() {
	*x = AddMaterialResponse{}
	mi := &file_proto_learning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMaterialResponse) ProtoMessage() {}

func (x *AddMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_learning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMaterialResponse.ProtoReflect.Descriptor instead.
func (*AddMaterialResponse) Descriptor() ([]byte, []int) {
	return file_proto_learning_proto_rawDescGZIP(), []int{1}
}

func (x *AddMaterialResponse) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

func (x *AddMaterialResponse) GetFlashcardsCreated() int32 {
	if x != nil {
		return x.FlashcardsCreated
	}
	return 0
}

type Flashcard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	Stage         int32                  `protobuf:"varint,4,opt,name=stage,proto3" json:"stage,omitempty"`
	NextReviewAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=next_review_at,json=nextReviewAt,proto3" json:"next_review_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flashcard) Reset() {
	*x = Flashcard{}
	mi := &file_proto_learning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flashcard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flashcard) ProtoMessage() {}

func (x *Flashcard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_learning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flashcard.ProtoReflect.Descriptor instead.
func (*Flashcard) Descriptor() ([]byte, []int) {
	return file_proto_learning_proto_rawDescGZIP(), []int{2}
}

func (x *Flashcard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Flashcard) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Flashcard) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *Flashcard) GetStage() int32 {
	if x != nil {
		return x.Stage
	}
	return 0
}

func (x *Flashcard) GetNextReviewAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextReviewAt
	}
	return nil
}

type FlashcardList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flashcards    []*Flashcard           `protobuf:"bytes,1,rep,name=flashcards,proto3" json:"flashcards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlashcardList) Reset() {
	*x = FlashcardList{}
	mi := &file_proto_learning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlashcardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashcardList) ProtoMessage() {}

func (x *FlashcardList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_learning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashcardList.ProtoReflect.Descriptor instead.
func (*FlashcardList) Descriptor() ([]byte, []int) {
	return file_proto_learning_proto_rawDescGZIP(), []int{3}
}

func (x *FlashcardList) GetFlashcards() []*Flashcard {
	if x != nil {
		return x.Flashcards
	}
	return nil
}

type CompleteReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlashcardId   string                 `protobuf:"bytes,1,opt,name=flashcard_id,json=flashcardId,proto3" json:"flashcard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteReviewRequest) Reset() {
	*x = CompleteReviewRequest{}
	mi := &file_proto_learning_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteReviewRequest) ProtoMessage() {}

func (x *CompleteReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_learning_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteReviewRequest.ProtoReflect.Descriptor instead.
func (*CompleteReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_learning_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteReviewRequest) GetFlashcardId() string {
	if x != nil {
		return x.FlashcardId
	}
	return ""
}

var File_proto_learning_proto protoreflect.FileDescriptor

const file_proto_learning_proto_rawDesc = "" +
	"\n" +
	"\x14proto/learning.proto\x12\blearning\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"B\n" +
	"\x12AddMaterialRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"e\n" +
	"\x13AddMaterialResponse\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\tR\n" +
	"materialId\x12-\n" +
	"\x12flashcards_created\x18\x02 \x01(\x05R\x11flashcardsCreated\"\xa7\x01\n" +
	"\tFlashcard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\tR\x06answer\x12\x14\n" +
	"\x05stage\x18\x04 \x01(\x05R\x05stage\x12@\n" +
	"\x0enext_review_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fnextReviewAt\"D\n" +
	"\rFlashcardList\x123\n" +
	"\n" +
	"flashcards\x18\x01 \x03(\v2\x13.learning.FlashcardR\n" +
	"flashcards\":\n" +
	"\x15CompleteReviewRequest\x12!\n" +
	"\fflashcard_id\x18\x01 \x01(\tR\vflashcardId2\xed\x01\n" +
	"\x0fLearningService\x12J\n" +
	"\vAddMaterial\x12\x1c.learning.AddMaterialRequest\x1a\x1d.learning.AddMaterialResponse\x12C\n" +
	"\x10GetDueFlashcards\x12\x16.google.protobuf.Empty\x1a\x17.learning.FlashcardList\x12I\n" +
	"\x0eCompleteReview\x12\x1f.learning.CompleteReviewRequest\x1a\x16.google.protobuf.EmptyB,Z*github.com/amityadav/landr/pkg/pb/learningb\x06proto3"

var (
	file_proto_learning_proto_rawDescOnce sync.Once
	file_proto_learning_proto_rawDescData []byte
)

func file_proto_learning_proto_rawDescGZIP() []byte {
	file_proto_learning_proto_rawDescOnce.Do(func() {
		file_proto_learning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_learning_proto_rawDesc), len(file_proto_learning_proto_rawDesc)))
	})
	return file_proto_learning_proto_rawDescData
}

var file_proto_learning_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_learning_proto_goTypes = []any{
	(*AddMaterialRequest)(nil),    // 0: learning.AddMaterialRequest
	(*AddMaterialResponse)(nil),   // 1: learning.AddMaterialResponse
	(*Flashcard)(nil),             // 2: learning.Flashcard
	(*FlashcardList)(nil),         // 3: learning.FlashcardList
	(*CompleteReviewRequest)(nil), // 4: learning.CompleteReviewRequest
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_proto_learning_proto_depIdxs = []int32{
	5, // 0: learning.Flashcard.next_review_at:type_name -> google.protobuf.Timestamp
	2, // 1: learning.FlashcardList.flashcards:type_name -> learning.Flashcard
	0, // 2: learning.LearningService.AddMaterial:input_type -> learning.AddMaterialRequest
	6, // 3: learning.LearningService.GetDueFlashcards:input_type -> google.protobuf.Empty
	4, // 4: learning.LearningService.CompleteReview:input_type -> learning.CompleteReviewRequest
	1, // 5: learning.LearningService.AddMaterial:output_type -> learning.AddMaterialResponse
	3, // 6: learning.LearningService.GetDueFlashcards:output_type -> learning.FlashcardList
	6, // 7: learning.LearningService.CompleteReview:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_learning_proto_init() }
func file_proto_learning_proto_init() {
	if File_proto_learning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_learning_proto_rawDesc), len(file_proto_learning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_learning_proto_goTypes,
		DependencyIndexes: file_proto_learning_proto_depIdxs,
		MessageInfos:      file_proto_learning_proto_msgTypes,
	}.Build()
	File_proto_learning_proto = out.File
	file_proto_learning_proto_goTypes = nil
	file_proto_learning_proto_depIdxs = nil
}
