// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: proto/learning.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { Empty } from "../google/protobuf/empty";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "learning";

export interface AddMaterialRequest {
  /** "TEXT" or "LINK" */
  type: string;
  content: string;
}

export interface AddMaterialResponse {
  materialId: string;
  flashcardsCreated: number;
}

export interface Flashcard {
  id: string;
  question: string;
  answer: string;
  stage: number;
  nextReviewAt: Date | undefined;
}

export interface FlashcardList {
  flashcards: Flashcard[];
}

export interface CompleteReviewRequest {
  flashcardId: string;
}

function createBaseAddMaterialRequest(): AddMaterialRequest {
  return { type: "", content: "" };
}

export const AddMaterialRequest: MessageFns<AddMaterialRequest> = {
  encode(message: AddMaterialRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.content !== "") {
      writer.uint32(18).string(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddMaterialRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddMaterialRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddMaterialRequest {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      content: isSet(object.content) ? globalThis.String(object.content) : "",
    };
  },

  toJSON(message: AddMaterialRequest): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddMaterialRequest>, I>>(base?: I): AddMaterialRequest {
    return AddMaterialRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddMaterialRequest>, I>>(object: I): AddMaterialRequest {
    const message = createBaseAddMaterialRequest();
    message.type = object.type ?? "";
    message.content = object.content ?? "";
    return message;
  },
};

function createBaseAddMaterialResponse(): AddMaterialResponse {
  return { materialId: "", flashcardsCreated: 0 };
}

export const AddMaterialResponse: MessageFns<AddMaterialResponse> = {
  encode(message: AddMaterialResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.materialId !== "") {
      writer.uint32(10).string(message.materialId);
    }
    if (message.flashcardsCreated !== 0) {
      writer.uint32(16).int32(message.flashcardsCreated);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddMaterialResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddMaterialResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.materialId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.flashcardsCreated = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddMaterialResponse {
    return {
      materialId: isSet(object.materialId) ? globalThis.String(object.materialId) : "",
      flashcardsCreated: isSet(object.flashcardsCreated) ? globalThis.Number(object.flashcardsCreated) : 0,
    };
  },

  toJSON(message: AddMaterialResponse): unknown {
    const obj: any = {};
    if (message.materialId !== "") {
      obj.materialId = message.materialId;
    }
    if (message.flashcardsCreated !== 0) {
      obj.flashcardsCreated = Math.round(message.flashcardsCreated);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddMaterialResponse>, I>>(base?: I): AddMaterialResponse {
    return AddMaterialResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddMaterialResponse>, I>>(object: I): AddMaterialResponse {
    const message = createBaseAddMaterialResponse();
    message.materialId = object.materialId ?? "";
    message.flashcardsCreated = object.flashcardsCreated ?? 0;
    return message;
  },
};

function createBaseFlashcard(): Flashcard {
  return { id: "", question: "", answer: "", stage: 0, nextReviewAt: undefined };
}

export const Flashcard: MessageFns<Flashcard> = {
  encode(message: Flashcard, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.question !== "") {
      writer.uint32(18).string(message.question);
    }
    if (message.answer !== "") {
      writer.uint32(26).string(message.answer);
    }
    if (message.stage !== 0) {
      writer.uint32(32).int32(message.stage);
    }
    if (message.nextReviewAt !== undefined) {
      Timestamp.encode(toTimestamp(message.nextReviewAt), writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Flashcard {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFlashcard();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.question = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.answer = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.stage = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.nextReviewAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Flashcard {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      question: isSet(object.question) ? globalThis.String(object.question) : "",
      answer: isSet(object.answer) ? globalThis.String(object.answer) : "",
      stage: isSet(object.stage) ? globalThis.Number(object.stage) : 0,
      nextReviewAt: isSet(object.nextReviewAt) ? fromJsonTimestamp(object.nextReviewAt) : undefined,
    };
  },

  toJSON(message: Flashcard): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.question !== "") {
      obj.question = message.question;
    }
    if (message.answer !== "") {
      obj.answer = message.answer;
    }
    if (message.stage !== 0) {
      obj.stage = Math.round(message.stage);
    }
    if (message.nextReviewAt !== undefined) {
      obj.nextReviewAt = message.nextReviewAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Flashcard>, I>>(base?: I): Flashcard {
    return Flashcard.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Flashcard>, I>>(object: I): Flashcard {
    const message = createBaseFlashcard();
    message.id = object.id ?? "";
    message.question = object.question ?? "";
    message.answer = object.answer ?? "";
    message.stage = object.stage ?? 0;
    message.nextReviewAt = object.nextReviewAt ?? undefined;
    return message;
  },
};

function createBaseFlashcardList(): FlashcardList {
  return { flashcards: [] };
}

export const FlashcardList: MessageFns<FlashcardList> = {
  encode(message: FlashcardList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.flashcards) {
      Flashcard.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FlashcardList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFlashcardList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.flashcards.push(Flashcard.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FlashcardList {
    return {
      flashcards: globalThis.Array.isArray(object?.flashcards)
        ? object.flashcards.map((e: any) => Flashcard.fromJSON(e))
        : [],
    };
  },

  toJSON(message: FlashcardList): unknown {
    const obj: any = {};
    if (message.flashcards?.length) {
      obj.flashcards = message.flashcards.map((e) => Flashcard.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FlashcardList>, I>>(base?: I): FlashcardList {
    return FlashcardList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FlashcardList>, I>>(object: I): FlashcardList {
    const message = createBaseFlashcardList();
    message.flashcards = object.flashcards?.map((e) => Flashcard.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCompleteReviewRequest(): CompleteReviewRequest {
  return { flashcardId: "" };
}

export const CompleteReviewRequest: MessageFns<CompleteReviewRequest> = {
  encode(message: CompleteReviewRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.flashcardId !== "") {
      writer.uint32(10).string(message.flashcardId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CompleteReviewRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompleteReviewRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.flashcardId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CompleteReviewRequest {
    return { flashcardId: isSet(object.flashcardId) ? globalThis.String(object.flashcardId) : "" };
  },

  toJSON(message: CompleteReviewRequest): unknown {
    const obj: any = {};
    if (message.flashcardId !== "") {
      obj.flashcardId = message.flashcardId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CompleteReviewRequest>, I>>(base?: I): CompleteReviewRequest {
    return CompleteReviewRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CompleteReviewRequest>, I>>(object: I): CompleteReviewRequest {
    const message = createBaseCompleteReviewRequest();
    message.flashcardId = object.flashcardId ?? "";
    return message;
  },
};

export interface LearningServiceImplementation<CallContextExt = {}> {
  addMaterial(
    request: AddMaterialRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<AddMaterialResponse>>;
  getDueFlashcards(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<FlashcardList>>;
  completeReview(request: CompleteReviewRequest, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
}

export interface LearningServiceClient<CallOptionsExt = {}> {
  addMaterial(
    request: DeepPartial<AddMaterialRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<AddMaterialResponse>;
  getDueFlashcards(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<FlashcardList>;
  completeReview(request: DeepPartial<CompleteReviewRequest>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
