// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: backend/proto/learning/learning.proto

package learning

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddMaterialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "TEXT", "LINK", "IMAGE", or "YOUTUBE"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ExistingTags  []string               `protobuf:"bytes,3,rep,name=existing_tags,json=existingTags,proto3" json:"existing_tags,omitempty"`
	ImageData     string                 `protobuf:"bytes,4,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"` // Base64 encoded image for IMAGE type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMaterialRequest) Reset() {
	*x = AddMaterialRequest{}
	mi := &file_backend_proto_learning_learning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMaterialRequest) ProtoMessage() {}

func (x *AddMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_learning_learning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMaterialRequest.ProtoReflect.Descriptor instead.
func (*AddMaterialRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_learning_learning_proto_rawDescGZIP(), []int{0}
}

func (x *AddMaterialRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddMaterialRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddMaterialRequest) GetExistingTags() []string {
	if x != nil {
		return x.ExistingTags
	}
	return nil
}

func (x *AddMaterialRequest) GetImageData() string {
	if x != nil {
		return x.ImageData
	}
	return ""
}

type AddMaterialResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MaterialId        string                 `protobuf:"bytes,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	FlashcardsCreated int32                  `protobuf:"varint,2,opt,name=flashcards_created,json=flashcardsCreated,proto3" json:"flashcards_created,omitempty"`
	Title             string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Tags              []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddMaterialResponse) Reset() {
	*x = AddMaterialResponse{}
	mi := &file_backend_proto_learning_learning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMaterialResponse) ProtoMessage() {}

func (x *AddMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_learning_learning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMaterialResponse.ProtoReflect.Descriptor instead.
func (*AddMaterialResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_learning_learning_proto_rawDescGZIP(), []int{1}
}

func (x *AddMaterialResponse) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

func (x *AddMaterialResponse) GetFlashcardsCreated() int32 {
	if x != nil {
		return x.FlashcardsCreated
	}
	return 0
}

func (x *AddMaterialResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddMaterialResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type DeleteMaterialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    string                 `protobuf:"bytes,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMaterialRequest) Reset() {
	*x = DeleteMaterialRequest{}
	mi := &file_backend_proto_learning_learning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMaterialRequest) ProtoMessage() {}

func (x *DeleteMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_learning_learning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMaterialRequest.ProtoReflect.Descriptor instead.
func (*DeleteMaterialRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_learning_learning_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteMaterialRequest) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

type MaterialSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	DueCount      int32                  `protobuf:"varint,3,opt,name=due_count,json=dueCount,proto3" json:"due_count,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterialSummary) Reset() {
	*x = MaterialSummary{}
	mi := &file_backend_proto_learning_learning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterialSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialSummary) ProtoMessage() {}

func (x *MaterialSummary) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_learning_learning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialSummary.ProtoReflect.Descriptor instead.
func (*MaterialSummary) Descriptor() ([]byte, []int) {
	return file_backend_proto_learning_learning_proto_rawDescGZIP(), []int{3}
}

func (x *MaterialSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MaterialSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MaterialSummary) GetDueCount() int32 {
	if x != nil {
		return x.DueCount
	}
	return 0
}

func (x *MaterialSummary) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetDueMaterialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDueMaterialsRequest) Reset() {
	*x = GetDueMaterialsRequest{}
	mi := &file_backend_proto_learning_learning_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDueMaterialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDueMaterialsRequest) ProtoMessage() {}

func (x *GetDueMaterialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_learning_learning_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDueMaterialsRequest.ProtoReflect.Descriptor instead.
func (*GetDueMaterialsRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_learning_learning_proto_rawDescGZIP(), []int{4}
}

func (x *GetDueMaterialsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetDueMaterialsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetDueMaterialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Materials     []*MaterialSummary     `protobuf:"bytes,1,rep,name=materials,proto3" json:"materials,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDueMaterialsResponse) Reset() {
	*x = GetDueMaterialsResponse{}
	mi := &file_backend_proto_learning_learning_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDueMaterialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDueMaterialsResponse) ProtoMessage() {}

func (x *GetDueMaterialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_learning_learning_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDueMaterialsResponse.ProtoReflect.Descriptor instead.
func (*GetDueMaterialsResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_learning_learning_proto_rawDescGZIP(), []int{5}
}

func (x *GetDueMaterialsResponse) GetMaterials() []*MaterialSummary {
	if x != nil {
		return x.Materials
	}
	return nil
}

func (x *GetDueMaterialsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetDueMaterialsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetDueMaterialsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetDueMaterialsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetDueFlashcardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    string                 `protobuf:"bytes,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDueFlashcardsRequest) Reset() {
	*x = GetDueFlashcardsRequest{}
	mi := &file_backend_proto_learning_learning_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDueFlashcardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDueFlashcardsRequest) ProtoMessage() {}

func (x *GetDueFlashcardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_learning_learning_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDueFlashcardsRequest.ProtoReflect.Descriptor instead.
func (*GetDueFlashcardsRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_learning_learning_proto_rawDescGZIP(), []int{6}
}

func (x *GetDueFlashcardsRequest) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

type Flashcard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	Stage         int32                  `protobuf:"varint,4,opt,name=stage,proto3" json:"stage,omitempty"`
	NextReviewAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=next_review_at,json=nextReviewAt,proto3" json:"next_review_at,omitempty"`
	MaterialTitle string                 `protobuf:"bytes,6,opt,name=material_title,json=materialTitle,proto3" json:"material_title,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flashcard) Reset() {
	*x = Flashcard{}
	mi := &file_backend_proto_learning_learning_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flashcard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flashcard) ProtoMessage() {}

func (x *Flashcard) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_learning_learning_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flashcard.ProtoReflect.Descriptor instead.
func (*Flashcard) Descriptor() ([]byte, []int) {
	return file_backend_proto_learning_learning_proto_rawDescGZIP(), []int{7}
}

func (x *Flashcard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Flashcard) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Flashcard) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *Flashcard) GetStage() int32 {
	if x != nil {
		return x.Stage
	}
	return 0
}

func (x *Flashcard) GetNextReviewAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextReviewAt
	}
	return nil
}

func (x *Flashcard) GetMaterialTitle() string {
	if x != nil {
		return x.MaterialTitle
	}
	return ""
}

func (x *Flashcard) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type FlashcardList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flashcards    []*Flashcard           `protobuf:"bytes,1,rep,name=flashcards,proto3" json:"flashcards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlashcardList) Reset() {
	*x = FlashcardList{}
	mi := &file_backend_proto_learning_learning_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlashcardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashcardList) ProtoMessage() {}

func (x *FlashcardList) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_learning_learning_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashcardList.ProtoReflect.Descriptor instead.
func (*FlashcardList) Descriptor() ([]byte, []int) {
	return file_backend_proto_learning_learning_proto_rawDescGZIP(), []int{8}
}

func (x *FlashcardList) GetFlashcards() []*Flashcard {
	if x != nil {
		return x.Flashcards
	}
	return nil
}

type CompleteReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlashcardId   string                 `protobuf:"bytes,1,opt,name=flashcard_id,json=flashcardId,proto3" json:"flashcard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteReviewRequest) Reset() {
	*x = CompleteReviewRequest{}
	mi := &file_backend_proto_learning_learning_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteReviewRequest) ProtoMessage() {}

func (x *CompleteReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_learning_learning_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteReviewRequest.ProtoReflect.Descriptor instead.
func (*CompleteReviewRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_learning_learning_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteReviewRequest) GetFlashcardId() string {
	if x != nil {
		return x.FlashcardId
	}
	return ""
}

type FailReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlashcardId   string                 `protobuf:"bytes,1,opt,name=flashcard_id,json=flashcardId,proto3" json:"flashcard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailReviewRequest) Reset() {
	*x = FailReviewRequest{}
	mi := &file_backend_proto_learning_learning_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailReviewRequest) ProtoMessage() {}

func (x *FailReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_learning_learning_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailReviewRequest.ProtoReflect.Descriptor instead.
func (*FailReviewRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_learning_learning_proto_rawDescGZIP(), []int{10}
}

func (x *FailReviewRequest) GetFlashcardId() string {
	if x != nil {
		return x.FlashcardId
	}
	return ""
}

type GetAllTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTagsResponse) Reset() {
	*x = GetAllTagsResponse{}
	mi := &file_backend_proto_learning_learning_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTagsResponse) ProtoMessage() {}

func (x *GetAllTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_learning_learning_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTagsResponse.ProtoReflect.Descriptor instead.
func (*GetAllTagsResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_learning_learning_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllTagsResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type NotificationStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DueFlashcardsCount int32                  `protobuf:"varint,1,opt,name=due_flashcards_count,json=dueFlashcardsCount,proto3" json:"due_flashcards_count,omitempty"`
	HasDueMaterials    bool                   `protobuf:"varint,2,opt,name=has_due_materials,json=hasDueMaterials,proto3" json:"has_due_materials,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NotificationStatusResponse) Reset() {
	*x = NotificationStatusResponse{}
	mi := &file_backend_proto_learning_learning_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationStatusResponse) ProtoMessage() {}

func (x *NotificationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_learning_learning_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationStatusResponse.ProtoReflect.Descriptor instead.
func (*NotificationStatusResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_learning_learning_proto_rawDescGZIP(), []int{12}
}

func (x *NotificationStatusResponse) GetDueFlashcardsCount() int32 {
	if x != nil {
		return x.DueFlashcardsCount
	}
	return 0
}

func (x *NotificationStatusResponse) GetHasDueMaterials() bool {
	if x != nil {
		return x.HasDueMaterials
	}
	return false
}

type GetMaterialSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    string                 `protobuf:"bytes,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMaterialSummaryRequest) Reset() {
	*x = GetMaterialSummaryRequest{}
	mi := &file_backend_proto_learning_learning_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaterialSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaterialSummaryRequest) ProtoMessage() {}

func (x *GetMaterialSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_learning_learning_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaterialSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetMaterialSummaryRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_learning_learning_proto_rawDescGZIP(), []int{13}
}

func (x *GetMaterialSummaryRequest) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

type GetMaterialSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMaterialSummaryResponse) Reset() {
	*x = GetMaterialSummaryResponse{}
	mi := &file_backend_proto_learning_learning_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaterialSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaterialSummaryResponse) ProtoMessage() {}

func (x *GetMaterialSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_learning_learning_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaterialSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetMaterialSummaryResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_learning_learning_proto_rawDescGZIP(), []int{14}
}

func (x *GetMaterialSummaryResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *GetMaterialSummaryResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UpdateFlashcardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlashcardId   string                 `protobuf:"bytes,1,opt,name=flashcard_id,json=flashcardId,proto3" json:"flashcard_id,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFlashcardRequest) Reset() {
	*x = UpdateFlashcardRequest{}
	mi := &file_backend_proto_learning_learning_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFlashcardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlashcardRequest) ProtoMessage() {}

func (x *UpdateFlashcardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_learning_learning_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlashcardRequest.ProtoReflect.Descriptor instead.
func (*UpdateFlashcardRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_learning_learning_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateFlashcardRequest) GetFlashcardId() string {
	if x != nil {
		return x.FlashcardId
	}
	return ""
}

func (x *UpdateFlashcardRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *UpdateFlashcardRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_backend_proto_learning_learning_proto protoreflect.FileDescriptor

const file_backend_proto_learning_learning_proto_rawDesc = "" +
	"\n" +
	"%backend/proto/learning/learning.proto\x12\blearning\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x86\x01\n" +
	"\x12AddMaterialRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12#\n" +
	"\rexisting_tags\x18\x03 \x03(\tR\fexistingTags\x12\x1d\n" +
	"\n" +
	"image_data\x18\x04 \x01(\tR\timageData\"\x8f\x01\n" +
	"\x13AddMaterialResponse\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\tR\n" +
	"materialId\x12-\n" +
	"\x12flashcards_created\x18\x02 \x01(\x05R\x11flashcardsCreated\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"8\n" +
	"\x15DeleteMaterialRequest\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\tR\n" +
	"materialId\"h\n" +
	"\x0fMaterialSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tdue_count\x18\x03 \x01(\x05R\bdueCount\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"I\n" +
	"\x16GetDueMaterialsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xc5\x01\n" +
	"\x17GetDueMaterialsResponse\x127\n" +
	"\tmaterials\x18\x01 \x03(\v2\x19.learning.MaterialSummaryR\tmaterials\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\":\n" +
	"\x17GetDueFlashcardsRequest\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\tR\n" +
	"materialId\"\xe2\x01\n" +
	"\tFlashcard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\tR\x06answer\x12\x14\n" +
	"\x05stage\x18\x04 \x01(\x05R\x05stage\x12@\n" +
	"\x0enext_review_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fnextReviewAt\x12%\n" +
	"\x0ematerial_title\x18\x06 \x01(\tR\rmaterialTitle\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\"D\n" +
	"\rFlashcardList\x123\n" +
	"\n" +
	"flashcards\x18\x01 \x03(\v2\x13.learning.FlashcardR\n" +
	"flashcards\":\n" +
	"\x15CompleteReviewRequest\x12!\n" +
	"\fflashcard_id\x18\x01 \x01(\tR\vflashcardId\"6\n" +
	"\x11FailReviewRequest\x12!\n" +
	"\fflashcard_id\x18\x01 \x01(\tR\vflashcardId\"(\n" +
	"\x12GetAllTagsResponse\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\"z\n" +
	"\x1aNotificationStatusResponse\x120\n" +
	"\x14due_flashcards_count\x18\x01 \x01(\x05R\x12dueFlashcardsCount\x12*\n" +
	"\x11has_due_materials\x18\x02 \x01(\bR\x0fhasDueMaterials\"<\n" +
	"\x19GetMaterialSummaryRequest\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\tR\n" +
	"materialId\"L\n" +
	"\x1aGetMaterialSummaryResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"o\n" +
	"\x16UpdateFlashcardRequest\x12!\n" +
	"\fflashcard_id\x18\x01 \x01(\tR\vflashcardId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\tR\x06answer2\xa7\x06\n" +
	"\x0fLearningService\x12J\n" +
	"\vAddMaterial\x12\x1c.learning.AddMaterialRequest\x1a\x1d.learning.AddMaterialResponse\x12I\n" +
	"\x0eDeleteMaterial\x12\x1f.learning.DeleteMaterialRequest\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\x0fGetDueMaterials\x12 .learning.GetDueMaterialsRequest\x1a!.learning.GetDueMaterialsResponse\x12N\n" +
	"\x10GetDueFlashcards\x12!.learning.GetDueFlashcardsRequest\x1a\x17.learning.FlashcardList\x12I\n" +
	"\x0eCompleteReview\x12\x1f.learning.CompleteReviewRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\n" +
	"FailReview\x12\x1b.learning.FailReviewRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\n" +
	"GetAllTags\x12\x16.google.protobuf.Empty\x1a\x1c.learning.GetAllTagsResponse\x12U\n" +
	"\x15GetNotificationStatus\x12\x16.google.protobuf.Empty\x1a$.learning.NotificationStatusResponse\x12_\n" +
	"\x12GetMaterialSummary\x12#.learning.GetMaterialSummaryRequest\x1a$.learning.GetMaterialSummaryResponse\x12K\n" +
	"\x0fUpdateFlashcard\x12 .learning.UpdateFlashcardRequest\x1a\x16.google.protobuf.EmptyB,Z*github.com/amityadav/landr/pkg/pb/learningb\x06proto3"

var (
	file_backend_proto_learning_learning_proto_rawDescOnce sync.Once
	file_backend_proto_learning_learning_proto_rawDescData []byte
)

func file_backend_proto_learning_learning_proto_rawDescGZIP() []byte {
	file_backend_proto_learning_learning_proto_rawDescOnce.Do(func() {
		file_backend_proto_learning_learning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_proto_learning_learning_proto_rawDesc), len(file_backend_proto_learning_learning_proto_rawDesc)))
	})
	return file_backend_proto_learning_learning_proto_rawDescData
}

var file_backend_proto_learning_learning_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_backend_proto_learning_learning_proto_goTypes = []any{
	(*AddMaterialRequest)(nil),         // 0: learning.AddMaterialRequest
	(*AddMaterialResponse)(nil),        // 1: learning.AddMaterialResponse
	(*DeleteMaterialRequest)(nil),      // 2: learning.DeleteMaterialRequest
	(*MaterialSummary)(nil),            // 3: learning.MaterialSummary
	(*GetDueMaterialsRequest)(nil),     // 4: learning.GetDueMaterialsRequest
	(*GetDueMaterialsResponse)(nil),    // 5: learning.GetDueMaterialsResponse
	(*GetDueFlashcardsRequest)(nil),    // 6: learning.GetDueFlashcardsRequest
	(*Flashcard)(nil),                  // 7: learning.Flashcard
	(*FlashcardList)(nil),              // 8: learning.FlashcardList
	(*CompleteReviewRequest)(nil),      // 9: learning.CompleteReviewRequest
	(*FailReviewRequest)(nil),          // 10: learning.FailReviewRequest
	(*GetAllTagsResponse)(nil),         // 11: learning.GetAllTagsResponse
	(*NotificationStatusResponse)(nil), // 12: learning.NotificationStatusResponse
	(*GetMaterialSummaryRequest)(nil),  // 13: learning.GetMaterialSummaryRequest
	(*GetMaterialSummaryResponse)(nil), // 14: learning.GetMaterialSummaryResponse
	(*UpdateFlashcardRequest)(nil),     // 15: learning.UpdateFlashcardRequest
	(*timestamppb.Timestamp)(nil),      // 16: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 17: google.protobuf.Empty
}
var file_backend_proto_learning_learning_proto_depIdxs = []int32{
	3,  // 0: learning.GetDueMaterialsResponse.materials:type_name -> learning.MaterialSummary
	16, // 1: learning.Flashcard.next_review_at:type_name -> google.protobuf.Timestamp
	7,  // 2: learning.FlashcardList.flashcards:type_name -> learning.Flashcard
	0,  // 3: learning.LearningService.AddMaterial:input_type -> learning.AddMaterialRequest
	2,  // 4: learning.LearningService.DeleteMaterial:input_type -> learning.DeleteMaterialRequest
	4,  // 5: learning.LearningService.GetDueMaterials:input_type -> learning.GetDueMaterialsRequest
	6,  // 6: learning.LearningService.GetDueFlashcards:input_type -> learning.GetDueFlashcardsRequest
	9,  // 7: learning.LearningService.CompleteReview:input_type -> learning.CompleteReviewRequest
	10, // 8: learning.LearningService.FailReview:input_type -> learning.FailReviewRequest
	17, // 9: learning.LearningService.GetAllTags:input_type -> google.protobuf.Empty
	17, // 10: learning.LearningService.GetNotificationStatus:input_type -> google.protobuf.Empty
	13, // 11: learning.LearningService.GetMaterialSummary:input_type -> learning.GetMaterialSummaryRequest
	15, // 12: learning.LearningService.UpdateFlashcard:input_type -> learning.UpdateFlashcardRequest
	1,  // 13: learning.LearningService.AddMaterial:output_type -> learning.AddMaterialResponse
	17, // 14: learning.LearningService.DeleteMaterial:output_type -> google.protobuf.Empty
	5,  // 15: learning.LearningService.GetDueMaterials:output_type -> learning.GetDueMaterialsResponse
	8,  // 16: learning.LearningService.GetDueFlashcards:output_type -> learning.FlashcardList
	17, // 17: learning.LearningService.CompleteReview:output_type -> google.protobuf.Empty
	17, // 18: learning.LearningService.FailReview:output_type -> google.protobuf.Empty
	11, // 19: learning.LearningService.GetAllTags:output_type -> learning.GetAllTagsResponse
	12, // 20: learning.LearningService.GetNotificationStatus:output_type -> learning.NotificationStatusResponse
	14, // 21: learning.LearningService.GetMaterialSummary:output_type -> learning.GetMaterialSummaryResponse
	17, // 22: learning.LearningService.UpdateFlashcard:output_type -> google.protobuf.Empty
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_backend_proto_learning_learning_proto_init() }
func file_backend_proto_learning_learning_proto_init() {
	if File_backend_proto_learning_learning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_proto_learning_learning_proto_rawDesc), len(file_backend_proto_learning_learning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_proto_learning_learning_proto_goTypes,
		DependencyIndexes: file_backend_proto_learning_learning_proto_depIdxs,
		MessageInfos:      file_backend_proto_learning_learning_proto_msgTypes,
	}.Build()
	File_backend_proto_learning_learning_proto = out.File
	file_backend_proto_learning_learning_proto_goTypes = nil
	file_backend_proto_learning_learning_proto_depIdxs = nil
}
