// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: proto/learning/learning.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { Empty } from "../../google/protobuf/empty";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "learning";

export interface AddMaterialRequest {
  /** "TEXT" or "LINK" */
  type: string;
  content: string;
  existingTags: string[];
}

export interface AddMaterialResponse {
  materialId: string;
  flashcardsCreated: number;
  title: string;
  tags: string[];
}

export interface MaterialSummary {
  id: string;
  title: string;
  dueCount: number;
  tags: string[];
}

export interface GetDueMaterialsResponse {
  materials: MaterialSummary[];
}

export interface GetDueFlashcardsRequest {
  materialId: string;
}

export interface Flashcard {
  id: string;
  question: string;
  answer: string;
  stage: number;
  nextReviewAt: Date | undefined;
  materialTitle: string;
  tags: string[];
}

export interface FlashcardList {
  flashcards: Flashcard[];
}

export interface CompleteReviewRequest {
  flashcardId: string;
}

export interface GetAllTagsResponse {
  tags: string[];
}

function createBaseAddMaterialRequest(): AddMaterialRequest {
  return { type: "", content: "", existingTags: [] };
}

export const AddMaterialRequest: MessageFns<AddMaterialRequest> = {
  encode(message: AddMaterialRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.content !== "") {
      writer.uint32(18).string(message.content);
    }
    for (const v of message.existingTags) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddMaterialRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddMaterialRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.existingTags.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddMaterialRequest {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      existingTags: globalThis.Array.isArray(object?.existingTags)
        ? object.existingTags.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: AddMaterialRequest): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.existingTags?.length) {
      obj.existingTags = message.existingTags;
    }
    return obj;
  },

  create(base?: DeepPartial<AddMaterialRequest>): AddMaterialRequest {
    return AddMaterialRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AddMaterialRequest>): AddMaterialRequest {
    const message = createBaseAddMaterialRequest();
    message.type = object.type ?? "";
    message.content = object.content ?? "";
    message.existingTags = object.existingTags?.map((e) => e) || [];
    return message;
  },
};

function createBaseAddMaterialResponse(): AddMaterialResponse {
  return { materialId: "", flashcardsCreated: 0, title: "", tags: [] };
}

export const AddMaterialResponse: MessageFns<AddMaterialResponse> = {
  encode(message: AddMaterialResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.materialId !== "") {
      writer.uint32(10).string(message.materialId);
    }
    if (message.flashcardsCreated !== 0) {
      writer.uint32(16).int32(message.flashcardsCreated);
    }
    if (message.title !== "") {
      writer.uint32(26).string(message.title);
    }
    for (const v of message.tags) {
      writer.uint32(34).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddMaterialResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddMaterialResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.materialId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.flashcardsCreated = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.tags.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddMaterialResponse {
    return {
      materialId: isSet(object.materialId) ? globalThis.String(object.materialId) : "",
      flashcardsCreated: isSet(object.flashcardsCreated) ? globalThis.Number(object.flashcardsCreated) : 0,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      tags: globalThis.Array.isArray(object?.tags) ? object.tags.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: AddMaterialResponse): unknown {
    const obj: any = {};
    if (message.materialId !== "") {
      obj.materialId = message.materialId;
    }
    if (message.flashcardsCreated !== 0) {
      obj.flashcardsCreated = Math.round(message.flashcardsCreated);
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.tags?.length) {
      obj.tags = message.tags;
    }
    return obj;
  },

  create(base?: DeepPartial<AddMaterialResponse>): AddMaterialResponse {
    return AddMaterialResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AddMaterialResponse>): AddMaterialResponse {
    const message = createBaseAddMaterialResponse();
    message.materialId = object.materialId ?? "";
    message.flashcardsCreated = object.flashcardsCreated ?? 0;
    message.title = object.title ?? "";
    message.tags = object.tags?.map((e) => e) || [];
    return message;
  },
};

function createBaseMaterialSummary(): MaterialSummary {
  return { id: "", title: "", dueCount: 0, tags: [] };
}

export const MaterialSummary: MessageFns<MaterialSummary> = {
  encode(message: MaterialSummary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.dueCount !== 0) {
      writer.uint32(24).int32(message.dueCount);
    }
    for (const v of message.tags) {
      writer.uint32(34).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MaterialSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMaterialSummary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.dueCount = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.tags.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MaterialSummary {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      dueCount: isSet(object.dueCount) ? globalThis.Number(object.dueCount) : 0,
      tags: globalThis.Array.isArray(object?.tags) ? object.tags.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: MaterialSummary): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.dueCount !== 0) {
      obj.dueCount = Math.round(message.dueCount);
    }
    if (message.tags?.length) {
      obj.tags = message.tags;
    }
    return obj;
  },

  create(base?: DeepPartial<MaterialSummary>): MaterialSummary {
    return MaterialSummary.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MaterialSummary>): MaterialSummary {
    const message = createBaseMaterialSummary();
    message.id = object.id ?? "";
    message.title = object.title ?? "";
    message.dueCount = object.dueCount ?? 0;
    message.tags = object.tags?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetDueMaterialsResponse(): GetDueMaterialsResponse {
  return { materials: [] };
}

export const GetDueMaterialsResponse: MessageFns<GetDueMaterialsResponse> = {
  encode(message: GetDueMaterialsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.materials) {
      MaterialSummary.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetDueMaterialsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetDueMaterialsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.materials.push(MaterialSummary.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetDueMaterialsResponse {
    return {
      materials: globalThis.Array.isArray(object?.materials)
        ? object.materials.map((e: any) => MaterialSummary.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetDueMaterialsResponse): unknown {
    const obj: any = {};
    if (message.materials?.length) {
      obj.materials = message.materials.map((e) => MaterialSummary.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<GetDueMaterialsResponse>): GetDueMaterialsResponse {
    return GetDueMaterialsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetDueMaterialsResponse>): GetDueMaterialsResponse {
    const message = createBaseGetDueMaterialsResponse();
    message.materials = object.materials?.map((e) => MaterialSummary.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetDueFlashcardsRequest(): GetDueFlashcardsRequest {
  return { materialId: "" };
}

export const GetDueFlashcardsRequest: MessageFns<GetDueFlashcardsRequest> = {
  encode(message: GetDueFlashcardsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.materialId !== "") {
      writer.uint32(10).string(message.materialId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetDueFlashcardsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetDueFlashcardsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.materialId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetDueFlashcardsRequest {
    return { materialId: isSet(object.materialId) ? globalThis.String(object.materialId) : "" };
  },

  toJSON(message: GetDueFlashcardsRequest): unknown {
    const obj: any = {};
    if (message.materialId !== "") {
      obj.materialId = message.materialId;
    }
    return obj;
  },

  create(base?: DeepPartial<GetDueFlashcardsRequest>): GetDueFlashcardsRequest {
    return GetDueFlashcardsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetDueFlashcardsRequest>): GetDueFlashcardsRequest {
    const message = createBaseGetDueFlashcardsRequest();
    message.materialId = object.materialId ?? "";
    return message;
  },
};

function createBaseFlashcard(): Flashcard {
  return { id: "", question: "", answer: "", stage: 0, nextReviewAt: undefined, materialTitle: "", tags: [] };
}

export const Flashcard: MessageFns<Flashcard> = {
  encode(message: Flashcard, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.question !== "") {
      writer.uint32(18).string(message.question);
    }
    if (message.answer !== "") {
      writer.uint32(26).string(message.answer);
    }
    if (message.stage !== 0) {
      writer.uint32(32).int32(message.stage);
    }
    if (message.nextReviewAt !== undefined) {
      Timestamp.encode(toTimestamp(message.nextReviewAt), writer.uint32(42).fork()).join();
    }
    if (message.materialTitle !== "") {
      writer.uint32(50).string(message.materialTitle);
    }
    for (const v of message.tags) {
      writer.uint32(58).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Flashcard {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFlashcard();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.question = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.answer = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.stage = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.nextReviewAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.materialTitle = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.tags.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Flashcard {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      question: isSet(object.question) ? globalThis.String(object.question) : "",
      answer: isSet(object.answer) ? globalThis.String(object.answer) : "",
      stage: isSet(object.stage) ? globalThis.Number(object.stage) : 0,
      nextReviewAt: isSet(object.nextReviewAt) ? fromJsonTimestamp(object.nextReviewAt) : undefined,
      materialTitle: isSet(object.materialTitle) ? globalThis.String(object.materialTitle) : "",
      tags: globalThis.Array.isArray(object?.tags) ? object.tags.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: Flashcard): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.question !== "") {
      obj.question = message.question;
    }
    if (message.answer !== "") {
      obj.answer = message.answer;
    }
    if (message.stage !== 0) {
      obj.stage = Math.round(message.stage);
    }
    if (message.nextReviewAt !== undefined) {
      obj.nextReviewAt = message.nextReviewAt.toISOString();
    }
    if (message.materialTitle !== "") {
      obj.materialTitle = message.materialTitle;
    }
    if (message.tags?.length) {
      obj.tags = message.tags;
    }
    return obj;
  },

  create(base?: DeepPartial<Flashcard>): Flashcard {
    return Flashcard.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Flashcard>): Flashcard {
    const message = createBaseFlashcard();
    message.id = object.id ?? "";
    message.question = object.question ?? "";
    message.answer = object.answer ?? "";
    message.stage = object.stage ?? 0;
    message.nextReviewAt = object.nextReviewAt ?? undefined;
    message.materialTitle = object.materialTitle ?? "";
    message.tags = object.tags?.map((e) => e) || [];
    return message;
  },
};

function createBaseFlashcardList(): FlashcardList {
  return { flashcards: [] };
}

export const FlashcardList: MessageFns<FlashcardList> = {
  encode(message: FlashcardList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.flashcards) {
      Flashcard.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FlashcardList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFlashcardList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.flashcards.push(Flashcard.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FlashcardList {
    return {
      flashcards: globalThis.Array.isArray(object?.flashcards)
        ? object.flashcards.map((e: any) => Flashcard.fromJSON(e))
        : [],
    };
  },

  toJSON(message: FlashcardList): unknown {
    const obj: any = {};
    if (message.flashcards?.length) {
      obj.flashcards = message.flashcards.map((e) => Flashcard.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<FlashcardList>): FlashcardList {
    return FlashcardList.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FlashcardList>): FlashcardList {
    const message = createBaseFlashcardList();
    message.flashcards = object.flashcards?.map((e) => Flashcard.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCompleteReviewRequest(): CompleteReviewRequest {
  return { flashcardId: "" };
}

export const CompleteReviewRequest: MessageFns<CompleteReviewRequest> = {
  encode(message: CompleteReviewRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.flashcardId !== "") {
      writer.uint32(10).string(message.flashcardId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CompleteReviewRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompleteReviewRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.flashcardId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CompleteReviewRequest {
    return { flashcardId: isSet(object.flashcardId) ? globalThis.String(object.flashcardId) : "" };
  },

  toJSON(message: CompleteReviewRequest): unknown {
    const obj: any = {};
    if (message.flashcardId !== "") {
      obj.flashcardId = message.flashcardId;
    }
    return obj;
  },

  create(base?: DeepPartial<CompleteReviewRequest>): CompleteReviewRequest {
    return CompleteReviewRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CompleteReviewRequest>): CompleteReviewRequest {
    const message = createBaseCompleteReviewRequest();
    message.flashcardId = object.flashcardId ?? "";
    return message;
  },
};

function createBaseGetAllTagsResponse(): GetAllTagsResponse {
  return { tags: [] };
}

export const GetAllTagsResponse: MessageFns<GetAllTagsResponse> = {
  encode(message: GetAllTagsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tags) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAllTagsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAllTagsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tags.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAllTagsResponse {
    return { tags: globalThis.Array.isArray(object?.tags) ? object.tags.map((e: any) => globalThis.String(e)) : [] };
  },

  toJSON(message: GetAllTagsResponse): unknown {
    const obj: any = {};
    if (message.tags?.length) {
      obj.tags = message.tags;
    }
    return obj;
  },

  create(base?: DeepPartial<GetAllTagsResponse>): GetAllTagsResponse {
    return GetAllTagsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetAllTagsResponse>): GetAllTagsResponse {
    const message = createBaseGetAllTagsResponse();
    message.tags = object.tags?.map((e) => e) || [];
    return message;
  },
};

export interface LearningServiceImplementation<CallContextExt = {}> {
  addMaterial(
    request: AddMaterialRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<AddMaterialResponse>>;
  getDueMaterials(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<GetDueMaterialsResponse>>;
  getDueFlashcards(
    request: GetDueFlashcardsRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<FlashcardList>>;
  completeReview(request: CompleteReviewRequest, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
  getAllTags(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<GetAllTagsResponse>>;
}

export interface LearningServiceClient<CallOptionsExt = {}> {
  addMaterial(
    request: DeepPartial<AddMaterialRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<AddMaterialResponse>;
  getDueMaterials(
    request: DeepPartial<Empty>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetDueMaterialsResponse>;
  getDueFlashcards(
    request: DeepPartial<GetDueFlashcardsRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<FlashcardList>;
  completeReview(request: DeepPartial<CompleteReviewRequest>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
  getAllTags(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<GetAllTagsResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
