// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: backend/proto/learning/learning.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { Empty } from "../../../google/protobuf/empty";
import { Timestamp } from "../../../google/protobuf/timestamp";

export const protobufPackage = "learning";

export interface AddMaterialRequest {
  /** "TEXT" or "LINK" */
  type: string;
  content: string;
  existingTags: string[];
}

export interface AddMaterialResponse {
  materialId: string;
  flashcardsCreated: number;
  title: string;
  tags: string[];
}

export interface Flashcard {
  id: string;
  question: string;
  answer: string;
  stage: number;
  nextReviewAt: Date | undefined;
  materialTitle: string;
  tags: string[];
}

export interface FlashcardList {
  flashcards: Flashcard[];
}

export interface CompleteReviewRequest {
  flashcardId: string;
}

function createBaseAddMaterialRequest(): AddMaterialRequest {
  return { type: "", content: "", existingTags: [] };
}

export const AddMaterialRequest: MessageFns<AddMaterialRequest> = {
  encode(message: AddMaterialRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.content !== "") {
      writer.uint32(18).string(message.content);
    }
    for (const v of message.existingTags) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddMaterialRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddMaterialRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.existingTags.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<AddMaterialRequest>): AddMaterialRequest {
    return AddMaterialRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AddMaterialRequest>): AddMaterialRequest {
    const message = createBaseAddMaterialRequest();
    message.type = object.type ?? "";
    message.content = object.content ?? "";
    message.existingTags = object.existingTags?.map((e) => e) || [];
    return message;
  },
};

function createBaseAddMaterialResponse(): AddMaterialResponse {
  return { materialId: "", flashcardsCreated: 0, title: "", tags: [] };
}

export const AddMaterialResponse: MessageFns<AddMaterialResponse> = {
  encode(message: AddMaterialResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.materialId !== "") {
      writer.uint32(10).string(message.materialId);
    }
    if (message.flashcardsCreated !== 0) {
      writer.uint32(16).int32(message.flashcardsCreated);
    }
    if (message.title !== "") {
      writer.uint32(26).string(message.title);
    }
    for (const v of message.tags) {
      writer.uint32(34).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddMaterialResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddMaterialResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.materialId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.flashcardsCreated = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.tags.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<AddMaterialResponse>): AddMaterialResponse {
    return AddMaterialResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AddMaterialResponse>): AddMaterialResponse {
    const message = createBaseAddMaterialResponse();
    message.materialId = object.materialId ?? "";
    message.flashcardsCreated = object.flashcardsCreated ?? 0;
    message.title = object.title ?? "";
    message.tags = object.tags?.map((e) => e) || [];
    return message;
  },
};

function createBaseFlashcard(): Flashcard {
  return { id: "", question: "", answer: "", stage: 0, nextReviewAt: undefined, materialTitle: "", tags: [] };
}

export const Flashcard: MessageFns<Flashcard> = {
  encode(message: Flashcard, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.question !== "") {
      writer.uint32(18).string(message.question);
    }
    if (message.answer !== "") {
      writer.uint32(26).string(message.answer);
    }
    if (message.stage !== 0) {
      writer.uint32(32).int32(message.stage);
    }
    if (message.nextReviewAt !== undefined) {
      Timestamp.encode(toTimestamp(message.nextReviewAt), writer.uint32(42).fork()).join();
    }
    if (message.materialTitle !== "") {
      writer.uint32(50).string(message.materialTitle);
    }
    for (const v of message.tags) {
      writer.uint32(58).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Flashcard {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFlashcard();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.question = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.answer = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.stage = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.nextReviewAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.materialTitle = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.tags.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Flashcard>): Flashcard {
    return Flashcard.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Flashcard>): Flashcard {
    const message = createBaseFlashcard();
    message.id = object.id ?? "";
    message.question = object.question ?? "";
    message.answer = object.answer ?? "";
    message.stage = object.stage ?? 0;
    message.nextReviewAt = object.nextReviewAt ?? undefined;
    message.materialTitle = object.materialTitle ?? "";
    message.tags = object.tags?.map((e) => e) || [];
    return message;
  },
};

function createBaseFlashcardList(): FlashcardList {
  return { flashcards: [] };
}

export const FlashcardList: MessageFns<FlashcardList> = {
  encode(message: FlashcardList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.flashcards) {
      Flashcard.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FlashcardList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFlashcardList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.flashcards.push(Flashcard.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FlashcardList>): FlashcardList {
    return FlashcardList.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FlashcardList>): FlashcardList {
    const message = createBaseFlashcardList();
    message.flashcards = object.flashcards?.map((e) => Flashcard.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCompleteReviewRequest(): CompleteReviewRequest {
  return { flashcardId: "" };
}

export const CompleteReviewRequest: MessageFns<CompleteReviewRequest> = {
  encode(message: CompleteReviewRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.flashcardId !== "") {
      writer.uint32(10).string(message.flashcardId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CompleteReviewRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompleteReviewRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.flashcardId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CompleteReviewRequest>): CompleteReviewRequest {
    return CompleteReviewRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CompleteReviewRequest>): CompleteReviewRequest {
    const message = createBaseCompleteReviewRequest();
    message.flashcardId = object.flashcardId ?? "";
    return message;
  },
};

export interface LearningServiceImplementation<CallContextExt = {}> {
  addMaterial(
    request: AddMaterialRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<AddMaterialResponse>>;
  getDueFlashcards(request: Empty, context: CallContext & CallContextExt): Promise<DeepPartial<FlashcardList>>;
  completeReview(request: CompleteReviewRequest, context: CallContext & CallContextExt): Promise<DeepPartial<Empty>>;
}

export interface LearningServiceClient<CallOptionsExt = {}> {
  addMaterial(
    request: DeepPartial<AddMaterialRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<AddMaterialResponse>;
  getDueFlashcards(request: DeepPartial<Empty>, options?: CallOptions & CallOptionsExt): Promise<FlashcardList>;
  completeReview(request: DeepPartial<CompleteReviewRequest>, options?: CallOptions & CallOptionsExt): Promise<Empty>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
